export interface Tao {
  chapter_number: string;
  poem: string[];
}

export const tao: Tao[] = [
  {
    chapter_number: '1',
    poem: [
      'The Dao [that] can be stated, is not the eternal Dao;',
      'The name [that] can be named, is not the eternal name.',
      'The nameless is the origin of the heaven and earth;',
      'The named is the mother of the myriad things.',
      'So,',
      'By constantly having no [desire] one views its wonders;',
      'By constantly having [desire], one views its limits.',
      'These two have the same origin, but they differ in name;',
      'Both are called Mystery.',
      'One Mystery plus another Mystery, are the sources of all wonders.',
    ],
  },

  {
    chapter_number: '2',
    poem: [
      'If everybody knows what beauty is,',
      'then beauty is not beauty [anymore];',
      'If everybody knows what goodness is,',
      'then goodness is not goodness [anymore].',
      'Therefore,',
      'Being and nothing give birth to one another,',
      'Hard and easy are mutually formed,',
      'Long and short shape each other,',
      'High and low complement each other,',
      'Music and voice are harmonized with each other,',
      'Front and back follow one another.',
      'Hence,',
      'The sage focuses on non-action in his works,',
      'Practices not-saying in his speech,',
      'The myriad things arise but are disregarded',
      'The sage produces but does not own',
      'Acts but does not claim',
      'Accomplishes work but does not focus on it',
      'Does not focus on it, and thus it does not go.',
    ],
  },

  {
    chapter_number: '3',
    poem: [
      'Not to quest for wealth',
      'will keep the people from rivalry.',
      'Not to prize things that are hard to come by',
      'will keep the people from becoming thieves.',
      'Not to manifest what you like and desire',
      'will make popular sentiments undisturbed.',
      "So, in the sages' peaceful and tranquil world,",
      "People's state of mind is calm,",
      'People live with enough food',
      "People's aspirations are lowered,",
      "People's physiques are strong;",
      'People will be unknowing, undesiring,',
      'And even the knowing ones will never dare to act,',
      'Action without action.',
      'There is nothing not done.',
    ],
  },

  {
    chapter_number: '4',
    poem: [
      'The Dao is empty,',
      'But when using it, it is impossible to use it up.',
      'It is profound, seems like the root of the myriad things.',
      'Blunts its own sharpness.',
      'Unravels its own fetters.',
      'Harmonises its own light.',
      'Mixes with its own dust.',
      'It is unclear, but seems to have existed there.',
      'I do not know whose son it is,',
      'Maybe it was already created before the creator.',
    ],
  },

  {
    chapter_number: '5',
    poem: [
      'The sky and the earth do not care,',
      'They regard the myriad things as straw dogs;',
      'The sage does not care,',
      'He regards people as straw dogs.',
      'The space between the sky and the earth, how much is it like large bellows!',
      'Empty but endless,',
      'Just move and wind will be produced;',
      'Much talk soon comes to nothing.',
      'It is better to be in between extremes.',
    ],
  },

  {
    chapter_number: '6',
    poem: [
      'The valley-spirit will not die, this is the primal mother.',
      'The gate of the primal mother is the root of the world.',
      'She unceasingly exists, her influence is without effort.',
    ],
  },
  {
    chapter_number: '7',
    poem: [
      'The sky and the earth / The universe is eternal.',
      'The reason for the eternal of the sky and the earth/the universe',
      'Is they are not being/existing alone,',
      'So they are eternal.',
      'Because of this, The sages put their selves behind all other people,',
      'Yet it is before all others he shall eventually stand.',
      'They were indifferent to the discomforts and dangers.',
      'Yet it is he who shall thus survive.',
      'It is none other than that they do not demand self.',
      'Yet it is he eventually who shall achieve for self.',
    ],
  },

  {
    chapter_number: '8',
    poem: [
      'The best quality/character is like water.',
      "The water's goodness is that it benefits the myriad things but does not quarrel,",
      'and it willingly goes to where others hate,',
      'Thus it is almost like the Dao.',
      'It is good to be/live on the ground,',
      'to deepen a heart,',
      'to love people while associating with them.',
      "to keep one's word while talking,",
      'to be peace while governing,',
      'to do what one is capable of,',
      'to act at a fit time.',
      'Because of the non-fighting-over,',
      'there will be no problem.',
    ],
  },

  {
    chapter_number: '9',
    poem: [
      'Rather than pour into a cup overflowed, It is better to stop it.',
      'To hammer and to sharpen, it will not be long to be broken.',
      'One cannot keep in eternal hiding a hall brimming with riches.',
      'The man arrogant from enormous wealth buries disaster upon his road.',
      'Removing after succeeding fits in with the Dao/principle of the universe.',
    ],
  },
  {
    chapter_number: '10',
    poem: [
      'If soul have been keeping on not being felt by the body,',
      'How can the body and the soul not part?',
      'Trying lungs to show [they are] delicate,',
      'How can they be like babies?',
      'Clean the mirror of ultimate source,',
      'How can they not found their defect?',
      'To love people and to govern the country,',
      'How not to appoint the Jih/Zhi/wise people?',
      'The gate of the heaven shuts and opens alternately and frequently,',
      'How to act like females?',
      'Have known all the causes and effects,',
      'How to keep doing only the backlog of things?',
      'Quicken them, feed them,',
      'Produce and do not own.',
      'Act and do not claim.',
      'Raise and do not rule.',
      'This is called profound virtue.',
    ],
  },

  {
    chapter_number: '11',
    poem: [
      'Put thirty spokes together to one hub,',
      'The original empty space makes the use of wheel.',
      'Knead clay into vessels,',
      'The original empty space makes the use of vessel.',
      'Shape door and windows for a house/room,',
      'The original empty space makes the use of house/room.',
      'So the things that are made are only conditions,',
      'What [we] are using is still the original empty space.',
    ],
  },

  {
    chapter_number: '12',
    poem: [
      "The beautiful colours make people's eyes blind,",
      "The appealing music makes people's ears deaf,",
      "The delicious flavours make people's mouth numb,",
      "To indulge in hunting makes people's heart wild,",
      "To pursue rare treasures makes people's behavior improper.",
      'So, as the sage attends to the inner world, not the outer world,',
      'Throw away the latter and adopt the former.',
    ],
  },

  {
    chapter_number: '13',
    poem: [
      'To appoint the person that is ploughed under is the same as to surprise [them],',
      'Respecting trusted subordinate is the same as respecting oneself.',
      'Why to appoint the person that is ploughed under is the same as to surprise [them]?',
      'Because to appoint is to regard the person as a subordinate,',
      'Getting appointed is being surprised, Being disfavored is also being surprised,',
      'This is why.',
      'Why respecting trusted subordinate is the same as respecting oneself?',
      'The reason that I have these trusted subordinate is I care about myself.',
      'If I do not care about myself, what trusted subordinate do I have?',
      'So, If [you] can change respecting yourself into respecting the world,',
      'then the world will be able to be reposed in you;',
      'If [you] can change loving yourself into loving the world,',
      'then the world will be able to be reposed in you.',
    ],
  },

  {
    chapter_number: '14',
    poem: [
      'That which is looked at yet never seen is known as invisible,',
      'That which is listened to yet never heard is known as soundless,',
      'And that which is grasped yet never touched is known as intangible.',
      'The origin of these three can not be observed, so mix them and form a unity.',
      'Above, it is not lit; Below, it is not dark.',
      'The Dao cannot be named by common rules, as it returns to its origin,',
      'It is the shape of the original shape, the image of the original object,',
      'This is blur and profound.',
      'Step forward, cannot see its beginning; Follow it, cannot see its end.',
      'Hold the ancient Dao to know the present things, and thus know the ancient beginnings,',
      'This is the principle of the Dao.',
    ],
  },

  {
    chapter_number: '15',
    poem: [
      'Once upon a time, those who knew the Way, were a mysterious and subtle people,',
      'Transient yet profound, tranquil yet utterly unfathomable.',
      'Since they are inexplicable, I can only tell what they seem like:',
      'Cautious, as if wading through a winter river,',
      'Wary, as if afraid of their own neighbours.',
      'Grave, like the courteous house guests.',
      'Elusive, as of melting ice.',
      'Pure and natural, as of unchiseled gems.',
      'Wide and open, as of a deep valley.',
      'Yet mysterious, oh yes, they were like troubled water.',
      'Who can remain tranquil amidst troubled airs, that calmness may flow from within?',
      'Who may remain at peace eternal, that motion would yield birth to nature?',
      'For those who follow the Way, fulfillment has never been their aim.',
      'Only as they are forever unfulfilled, can such freshness be ever renewed.',
    ],
  },

  {
    chapter_number: '16',
    poem: [
      "Immersed within the heart of the void, keep tranquility's essence.",
      'The myriad things together arise,',
      'I thereby perceive their returning.',
      'Now things flower, and in flowering each one returns to the source,',
      'The returning to the source is called tranquillity,',
      'This is the returning to destiny,',
      'The returning to destiny is the eternal,',
      'To know the eternal is wisdom,',
      'When one does not know wisdom, disaster arises!',
      'Knowing the eternal is wide-ranging,',
      'Wide-ranging means open-minded,',
      'Open-minded means royal,',
      'Royal means heavenly,',
      'Heavenly means the Dao,',
      'The Dao means everlasting.',
      'Bodiless and without form, cannot wither or perish.',
    ],
  },

  {
    chapter_number: '17',
    poem: [
      'Great rulers are hardly known by their subjects,',
      'Then come those the people draw near and praise,',
      'Then those the people hold in fear,',
      'Then those the people revile.',
      'When one lacks trust, one finds no trust.',
      'Reluctantly, without boasting;',
      'Perform actions, accomplish deeds;',
      'The people will say it happened naturally.',
    ],
  },

  {
    chapter_number: '18',
    poem: [
      'When the Dao is lost, so there arises benevolence and righteousness.',
      'When prudence and wisdom appear, there is great hypocrisy.',
      'When family relations are not right, there is filial piety and paternal affection.',
      'When the state is confused and chaotic, there is loyalty and faithfulness.',
    ],
  },

  {
    chapter_number: '19',
    poem: [
      'Abandon holiness, relinquish prudence; the people will flourish a hundredfold,',
      'Abandon benevolence, relinquish righteousness; and people will return to filial piety and affection.',
      'Abandon cleverness, relinquish gain; and thieves and robbers will not appear.',
      'As I know such three to be no mere words,',
      'Stay true to that which is reliable.',
      'Recognise simplicity, embrace purity,',
      'Lessen the self, diminish desires.',
    ],
  },

  {
    chapter_number: '20',
    poem: [
      'Discard conventional doctrines and be relieved from anxieties.',
      'Approval or flattery, what difference does it make?',
      'Good or evil, what difference does it take?',
      'Just because the people are at awe, you cannot be indifferent?',
      'Ridiculous! Ungrounded!',
      'When everyone is celebrating and joyous,',
      'As if relishing a spiritual triumph,',
      'As if enjoying a victorious feast.',
      'I alone am peaceful! Contemplating the myriad future,',
      'Dazed like a newborn child,',
      'Seizing the moment! Pondering the uncertainties.',
      'When everyone feels lavished,',
      'I alone am hollowed.',
      'I am a fool! Confounded!',
      'When everyone seemed enlightened, I alone am in suspense;',
      'When everyone is watchful, I alone become restful.',
      'Enigmatic! Like the obscure twilight,',
      'Desolate! Like the infinite universe.',
      'When everyone is focused, I alone am playful and trivial.',
      'I alone am different from the common,',
      'I find refuge in the womb of this profound conception.',
    ],
  },

  {
    chapter_number: '21',
    poem: [
      'Where the greatest Virtue resides,',
      'Only the Dao may reveal.',
      'Things that bestow the Dao,',
      'Radiates such liberty, such easiness.',
      'Eased! Liberated from its form, yet fashioned;',
      'Liberated! At ease with its position, yet poised.',
      'Mesmerizing! Mysterious!',
      'Brilliance from within;',
      'Its brilliance so enlightening, it exemplifies the truth.',
      'Traversing through all times,',
      'Its name is not diminished,',
      'Amassing all marvels of human intelligence.',
      'How do I know the essence of all marvels?',
      'By observing things that bestow the Dao.',
    ],
  },

  {
    chapter_number: '22',
    poem: [
      'Fractured, one asserts unity,',
      'Crooked, one acts straight,',
      'Depressed, one appears fulfilled,',
      'Exhausted, one exhibit freshness,',
      'Ignorant, one expresses intelligence,',
      'Excessive, one becomes delusive,',
      'Hence, the master maintains integrity,',
      'And sets an example for the people.',
      'Profess not and reveal enlightenment,',
      'Contend not and lavish brilliance,',
      'Proclaim not and win praises,',
      'Dignify not and garner respect.',
      'The master contests not,',
      'Therefore is uncontested.',
      '“Fractured, one asserts unity”,',
      'Such timeless truth!',
      'With genuine integrity, one rediscovers self.',
    ],
  },

  {
    chapter_number: '23',
    poem: [
      'Less spoken, words speak for themselves naturally.',
      'Therefore gusts cannot chill the exuberant day,',
      'Showers cannot turn day to dusk.',
      'Why is it so?',
      'Even the heaven and earth cannot counter its own force,',
      'Let alone people?',
      'Therefore those engaged with the Dao takes pleasure that,',
      'The Taught is the Dao,',
      'The Virtuous is the Virtue,',
      'The perplexed is perplexity.',
      'At one with the Dao, the Dao is welcoming;',
      'At one with Virtue, Virtue be appreciating;',
      'At one with perplexity, perplexity be gratifying.',
      'Lack of belief,',
      'Explains the disbelief in this futility.',
    ],
  },

  {
    chapter_number: '24',
    poem: [
      'Ones who reach do not stand,',
      'Ones who stride do not pace,',
      'Ones self-seeing are not enlightened,',
      'Ones self-possessed are not established.',
      'Ones self-asserted are without accomplishments,',
      'Ones self-esteemed are without respect.',
      'These according to the Dao,',
      'Are called extravagance and exorbitance.',
      'Materialistic matters alike are resented,',
      'Therefore those embracing Art dwells not.',
    ],
  },

  {
    chapter_number: '25',
    poem: [
      'Mired into existence,',
      'Before the conception of heaven and earth,',
      'Tranquil! Desolate!',
      'Independent and undeterred,',
      'Cyclical and not circumvented,',
      'As being the mother of all nature.',
      'Its name is unbeknown,',
      'I call it the Art of the Dao',
      'And arbitrarily describe it as great.',
      'Being great, it is desolated,',
      'Being desolated, it is removed,',
      'Being removed, it returns.',
      'Therefore the Art is great,',
      'Heaven is great,',
      'Earth is great,',
      'The master is also great.',
      'These are the four noble greatness,',
      'And the master is one of them.',
      'The master is inspired by the underlying principles of the earth,',
      'The earth is inspired by the underlying principles of the heavens,',
      'The heavens are inspired by the underlying principles of the Dao,',
      'Art is inspired by the underlying principles.',
    ],
  },

  {
    chapter_number: '26',
    poem: [
      'Weightiness is the root of weightlessness,',
      'Temperance is the master of temperament.',
      'Therefore the master stays close to trusted supplies in expeditions;',
      'There be spectacles and scenery,',
      'Presiding in serenity.',
      'Why then would a leader of a myriad supporters,',
      'Put no weight on the well being of its people?',
      'Weightless, and lose authority,',
      'Tempestuous, and forfeit mastership.',
    ],
  },

  {
    chapter_number: '27',
    poem: [
      'Good traveling leaves no tracks;',
      'Good speech is without reproach;',
      'Good strategies need no plotting;',
      'With good fastening, even a door with no hinge cannot be opened;',
      'The good knot is made without a rope and cannot be unravelled.',
      'Hence the Sage never fails in saving people,',
      'Therefore no one is rejected;',
      'The Sage never fails at saving things,',
      'Therefore nothing is left abandoned,',
      'This is illumination.',
      'Thus the good people are the teachers of the bad;',
      'The bad people are resources for the good.',
      'One who fails to respect his teacher,',
      'And does not cherish his resources,',
      'However intelligent such a one may be, he is still greatly confused.',
      'This is the essential mystery!',
    ],
  },

  {
    chapter_number: '28',
    poem: [
      'Acquire knowledge of extroversions, but',
      'Acquaint with introversions, and',
      "Be the earth's fountain.",
      "Be the earth's fountain, be Virtuous and undeterred,",
      'And be reborn.',
      'Realize the radiance of the limelight, but',
      'Remain in the shadows, and',
      "Be the people's example.",
      "Be the people's example, be Virtuous and not excessive,",
      'And be tranquilized.',
      'Experience the glory, but',
      'Express humility, and',
      "Be the world's refuge.",
      "Be the world's refuge, be Virtuous and complacent,",
      'And be returned to your roots.',
      'Uprooted, wood can be carved into instruments,',
      'The master utilizes it and become respectful leaders.',
      'Therefore, a great tailor seldom trims.',
    ],
  },

  {
    chapter_number: '29',
    poem: [
      'It is futile trying to possess the universe,',
      "And act on shaping it in the direction of one's ambition.",
      'The instruments of the universe cannot be shaped,',
      'One cannot act upon it.',
      'Act upon it and you will fail,',
      'Grasp onto it and it will slip.',
      'For everything, there is a time to tread; a time to trail,',
      'A time to gust; a time to gape,',
      'A time to vigor; a time to vice,',
      'A time to carry; a time to ride.',
      'Hence the master departs extremes.',
      'Departs extravagance, departs magnificence.',
    ],
  },

  {
    chapter_number: '30',
    poem: [
      'Ones who offer advice in the Art of governance,',
      'Offers not the use of forces to dominate the world,',
      'Understanding its invitation to retaliation.',
      'Where troops tramp, thorns thrive.',
      'After great battalions, years of resentments are inevitable.',
      'Therefore the master bring to fruition and leave be,',
      'Daring not to capture dominance.',
      'Accomplish and refrain glorification,',
      'Accomplish and restrain aggression,',
      'Accomplish and relinquish pride,',
      'Accomplish and take no credit,',
      'Accomplish and refuse domination.',
      'Matters that mature grow old,',
      'That is not in the Art of the Dao,',
      'Without the Art of being, and be premature.',
    ],
  },

  {
    chapter_number: '31',
    poem: [
      'Where everyone is well armed, is a state in vain,',
      'Matters alike are resented,',
      'Therefore the master dwells not.',
      'Hence the master finds residence on leftovers,',
      'Mobilizes on righteousness.',
      'Armaments, are instruments in vain,',
      'Are unmasterly instruments.',
      'Wielded only when inevitable,',
      'Reconciliation is paramount,',
      'Victorious without glorification.',
      'Those who glorify, take pleasure in massacres.',
      'Those who take pleasure in massacres,',
      'Cannot win the hearts of the people.',
      'Therefore, upon prosperity, be left-out,',
      'In adversity, be righteous.',
      'Hence the general is to the left,',
      'The admiral is to the right,',
      'Positioned in solemn remembrance.',
      'Casualties, are mourned in consolation.',
      'Victories, are remembered in solemness.',
    ],
  },

  {
    chapter_number: '32',
    poem: [
      'The Art of the Dao is nameless.',
      'Bushes of thorns may be humble,',
      'Yet no one dares belittle its sting.',
      'When leaders abide,',
      'The myriad things things follow.',
      'Heaven and earth complements another,',
      'Morning dew befalls,',
      'People, without ordinance, becomes orderly.',
      'Orders are identified by classifications;',
      'Once the classes are identified, one soon sees the limitations.',
      'Knowing the limitations, thus become unlimited.',
      'Like that where the Art is manifested in the world,',
      'Is there where rivers merge into oceans.',
    ],
  },

  {
    chapter_number: '33',
    poem: [
      'Knowing people is being intelligent,',
      'Knowing self is being enlightened.',
      'Victorious over people is being powerful,',
      'Victorious over self is being invincible.',
      'Those who are content are submerged in wealth,',
      'Those who are contentious are submitted to ambitions,',
      'Those who do not forget their principles endure,',
      'Those who die but are not forgotten live on.',
    ],
  },

  {
    chapter_number: '34',
    poem: [
      'Implications of the Dao are broad and extensive. Ubiquitous!',
      'Capable of contravening and swaying anything left or right.',
      'The myriad things depend on it yet it never turns its back away,',
      'Fulfilling without recognitions.',
      'Submitting to the myriad things without assuming ownership,',
      'Always undesirous,',
      'Thus be called modest;',
      'Submerged by the myriad things without accepting ownership,',
      'Thus be called great.',
      'Hence the master foregoes greatness,',
      'Therefore is capable of accomplishing great deeds.',
    ],
  },

  {
    chapter_number: '35',
    poem: [
      'Herald a great icon,',
      'And the people cometh;',
      'Cometh towards unharmful doctrines,',
      'People find security,',
      'Peacefulness and prosperity.',
      'Music and enticements craves the visitor to stay.',
      'The words of the Dao,',
      'Are tasteless and lack sensations,',
      'Observe and it cannot be seen,',
      'Listen and it cannot be heard,',
      'Exploit and it cannot be exhausted.',
    ],
  },

  {
    chapter_number: '36',
    poem: [
      'That about to wither, must have bloomed;',
      'That about to falter, must have dominated;',
      'That about to be abandoned, must have been promoted;',
      'That about to be taken away, must have been given to.',
      'This is being enlightened by the trivialities.',
      'Gentleness overcomes harshness,',
      'vulnerability overcomes dominance.',
      'As fishes should not be removed from the depths,',
      'Live ammunition should not be exposed for demonstrations.',
    ],
  },

  {
    chapter_number: '37',
    poem: [
      'The Dao acts not and leaves none to act upon.',
      'When the leaders abide,',
      'The myriad things transpire;',
      'Transpired, they start desiring for achievements,',
      'Such desires tranquilized only by unassuming integrity',
      'With unassuming integrity one becomes undesirous;',
      'Undesirous, and be tranquilized,',
      'The world consequentially becomes righteous.',
    ],
  },

  {
    chapter_number: '38',
    poem: [
      'Those with great Virtue are not bound by virtues,',
      'Thus can be with Virtue;',
      'Those without Virtue fail to liberate themselves of virtues,',
      'Thus remain without Virtue.',
      'Those with great Virtue act not and take no credit in their actions,',
      'Those without Virtue act and demand respect in their actions.',
      'The humane acts charitably and holds no repute.',
      'The righteous acts in the name of justice and relishes the glory.',
      'The moral acts, and when there is no response,',
      'Forces the issue, alas to no avail.',
      'Therefore, when the Dao is lost there is Virtue,',
      'When Virtue is lost there is humanity,',
      'When humanity is lost there is righteousness,',
      'When righteousness is lost there is morality.',
      'When the rituals of morality become customary,',
      'Devotion and faith become skin deep and turmoil begins to stir;',
      'When priority is given to the scholars,',
      'The Dao becomes glorified and are used to fool the crowd.',
      'Hence the master is concerned with depth,',
      'Not with sheerness;',
      'Dwells on integrity, not on glory.',
      'Therefore, detach from exteriors and embrace interiors.',
    ],
  },

  {
    chapter_number: '39',
    poem: [
      'When at one with the Dao:',
      'When heaven is at one, it is clear,',
      'When earth is at one, it is fertile,',
      'When the spirit is at one, it is serene,',
      'When the refuge is at one, it is rewarding,',
      'When the myriad things are at one, there is life,',
      'When the leaders are at one, the people are respectable,',
      'And become at one!',
      'If the heaven is unclear, there is fear it will fracture;',
      'If the earth is infertile, there is dread for disaster;',
      'If the spirit is disturbed, there is anxiety in death;',
      'If the refuge is deprived, there is panic over recession;',
      'If the myriad things are lifeless, there is scare of extermination;',
      'If the leaders are disrespectful,',
      'absorbed in the admiration',
      'of their own supremacy, the people becomes terrorized by authority.',
      'Therefore admiration is based on humility,',
      'Supremacy finds foundation in lowliness.',
      'When the leaders maintain uninvolved, irrelevant and undeserving,',
      'Is it not based on humility?',
      'Therefore prepare your chariots and set them aside.',
      'Yearn not for crowns and jewels,',
      'And remain composed in grits and gravel.',
    ],
  },

  {
    chapter_number: '40',
    poem: [
      'Resilience is the Dao in action,',
      'Vulnerability is the Dao in expression.',
      'The myriad things in the universe are conceived by existence,',
      'Existence is conceived by inexistence.',
    ],
  },

  {
    chapter_number: '41',
    poem: [
      'The learned discovers the Dao, duly obliges;',
      'The learning discovers the Dao, and questions its potency;',
      'The unlearned discovers the Dao, and roars into laughter,',
      'Without the laughs, it would not be the Dao.',
      'Therefore words of wisdom goes:',
      'Those enlightened by the Dao seem confused,',
      'Those progressing towards the Dao seem to fall behind,',
      'Those who discredit the Dao seem honourable,',
      'Those Virtuous seem desolate,',
      'Those honest seem humiliated,',
      'Those with noble Virtue seem lacking,',
      'Those building on Virtue seem fraudulent,',
      'Those of principled character seem to waver,',
      'Great squareness is without turning corners,',
      'Great instruments are deliberately constructed,',
      'Great vocalists seldom raise their voices,',
      'Great icons are shapeless.',
      'The Dao is a master of provisioning and empowerment.',
    ],
  },

  {
    chapter_number: '42',
    poem: [
      'The Dao provisions unity,',
      'Unity provisions duality,',
      'Duality provisions trinity,',
      'Trinity provisions the myriad things.',
      'The myriad things bear shadows and embrace radiance,',
      'Are infused with the breath of life to achieve the harmonized trinity of darkness, light and soul.',
      '(People hate to be uninvolved, irrelevant and undeserving,',
      'Yet true leaders associate themselves with these characters.)',
      'Therefore, things may be gained by losing,',
      'May be lost by gaining.',
      'What others profess, I will also proclaim:',
      '“Forced principles will not be viable”,',
      'Let this be the heart and soul of the message.',
    ],
  },

  {
    chapter_number: '43',
    poem: [
      "The world's softest,",
      "Steers the world's hardest,",
      'That with no substance enters there with no space,',
      'Hence come to the appreciation of the benefits of inaction.',
      'Doctrines of unspoken words,',
      'Benefits of inaction,',
      'Rarely in this world could anything compare.',
    ],
  },

  {
    chapter_number: '44',
    poem: [
      'Fame and honour, which is more associable?',
      'Health and wealth, which is more vital?',
      'Success and failure, which is more harmful?',
      'Hence intense admiration comes with a hefty price,',
      'Accumulation of treasures comes with the loss of modesty.',
      'Acquaint with humility and be unhumiliated,',
      'Know the limitations and be unlimited, be lasting.',
    ],
  },

  {
    chapter_number: '45',
    poem: [
      'Great support seems deficient,',
      'Employed it will not collapse;',
      'Great buoyancy seems empty,',
      'Utilized it will not be exhausted.',
      'Great honesty seems corrupt,',
      'Great skills seem incompetent,',
      'Great orations seem inarticulate.',
      'Movement overcomes coldness,',
      'Stillness overcomes heat,',
      'Tranquility makes the world become righteous.',
    ],
  },

  {
    chapter_number: '46',
    poem: [
      'When the world is with the Dao,',
      'Carriages are used to transport manure;',
      'When the world is without the Dao,',
      'Armed chariots are lined up near the city gates.',
      'There is no greater sin than seduction,',
      'No greater fault than discontentment,',
      'No greater guilt than yearning.',
      'Therefore know what is enough, and you will always have enough.',
    ],
  },

  {
    chapter_number: '47',
    poem: [
      'Without leaving home,',
      'You may be acquainted with the universe;',
      'Without prying into windows of knowledge,',
      'You may be acquainted with the Dao.',
      'The further you may travel, the less you might know.',
      'Hence the master travels not, yet knowledgeable,',
      'Sees not, yet pronounced,',
      'Acts not, yet accomplished.',
    ],
  },

  {
    chapter_number: '48',
    poem: [
      'Practicing scholarships, everyday there is something to gain,',
      'Practicing the Dao, everyday there is something to lose;',
      'When you lose all that can be lost,',
      'You may be without action.',
      'Act not and leave none to be acted upon!',
      'Therefore those who can master the universe,',
      'Often remain unoccupied;',
      'Those who are preoccupied,',
      'Cannot master the universe.',
    ],
  },

  {
    chapter_number: '49',
    poem: [
      'The master never close up their mind,',
      "But base their mind on the people's mind.",
      'Those kind, be kind to them,',
      'Those unkind, be kind to them also.',
      'Virtuous is being kind.',
      'Those faithful, have faith in them,',
      'Those unfaithful, have faith in them also.',
      'Virtuous is having faith.',
      'The master is always anxious with the world about,',
      'And is concerned with the people.',
      "The people attends to the master's words and expressions,",
      'The master fosters all in innocence.',
    ],
  },

  {
    chapter_number: '50',
    poem: [
      'Battling between life and death:',
      'Three of ten believe they will live,',
      'Three of ten believe they will die,',
      'There are also three of ten who believe that being born,',
      'Is the beginning of the journey towards death.',
      'Why is it so?',
      'Because being alive is treasured heavily.',
      'Those who truly know how to capture the essence of living,',
      'Travels through the woods without being attacked by tigers,',
      'Enters into battlefields without requiring armours;',
      'Brutality has no angle to strike,',
      'Tigers find no place to lay their claws,',
      'Enemies find no opening to lodge their swords.',
      'Why is it so?',
      'Because there is no room for death.',
    ],
  },

  {
    chapter_number: '51',
    poem: [
      'The Dao conceives,',
      'Virtue provisions,',
      'Matters shape,',
      'Movements empower.',
      'Hence for the myriad things,',
      'There is none that does not respect the Dao and honour Virtue.',
      'Respect for the Dao,',
      'Honour given to Virtue,',
      'Are not commanded, yet they come about naturally.',
      'Therefore the Dao conceives and Virtue provisions,',
      'Leads and educates,',
      'Empowers and ripens,',
      'Raises and redeems.',
      'Conceive and not possess,',
      'Act and not dwell,',
      'Lead and not dictate,',
      'These are the intricacies of Virtue.',
    ],
  },

  {
    chapter_number: '52',
    poem: [
      'The origin of existence began with the mother of all nature.',
      'Understand the mother,',
      'And get to know the being of the child;',
      'Understand the being of the child,',
      'Then reacquaint with the mother,',
      'Without being, be unlimited.',
      'Clutter the exchanges,',
      'Close the doors,',
      'Live to be without office.',
      'Open the exchanges',
      'Operate the businesses,',
      'Live to be without relief.',
      'Seeing to little things is to have insight,',
      'Keeping to gentleness is to have strength.',
      'Exploit the radiance,',
      'But return to your insight,',
      'Remember that trying to leave nothing behind leaves yourself in vain,',
      'That is practicing the timeless truth.',
    ],
  },

  {
    chapter_number: '53',
    poem: [
      'That which makes one principled is having knowledge,',
      'Walking the way of the Dao,',
      'The only fear is to become instructive.',
      'The way towards the Dao is unpaved,',
      'Yet people like having a path.',
      'When many are appointed to offices, while fields sprout weed,',
      'Storages are empty,',
      'Fashions are blatantly accessorized,',
      'People carry weaponry,',
      'Are satiated in feasts,',
      'Lavished with extravaganzas,',
      'That is making out like bandits!',
      'Not the way of the Dao.',
    ],
  },

  {
    chapter_number: '54',
    poem: [
      'Proficient builders do not eradicate,',
      'Noble embracers do not abandon,',
      'They continue to be honoured from generation to generation.',
      'Cultivate the Dao amidst your self,',
      'The Virtue is in understanding the truth;',
      'Cultivate the Dao amidst your family,',
      'The Virtue is in finding fortune;',
      'Cultivate the Dao amidst your community,',
      'The Virtue is in garnering respect;',
      'Cultivate the Dao amidst your nation,',
      'The Virtue is in harvesting prosperity.',
      'Cultivate the Dao amidst the universe,',
      'The Virtue is ubiquitously enjoyed.',
      "Therefore, behold one's self to see self,",
      "Behold one's family to see family,",
      "Behold one's community to see community,",
      "Behold one's nation to see nationality,",
      'Behold the universe to see the universe.',
      'How do I know the essence of the universe?',
      'By seeing this.',
    ],
  },

  {
    chapter_number: '55',
    poem: [
      'The profoundness of being embraced with the Virtue,',
      'Is like a being a newborn.',
      'Wild wasps, poisonous scorpions, venomous snakes will find no sting,',
      'Fierce beasts will find no hold,',
      'Preying birds will find no claws.',
      'The bones are weak, the muscles are tender, yet the grip is firm.',
      'Knows not of the union of male and female,',
      'Yet wholly united with integrity, the very essence of exquisiteness.',
      'Cries all day, yet the voice is not hoarsened,',
      'The very chorus of harmony.',
      'Understanding harmony is being eternal,',
      'Understanding eternity is being enlightened,',
      'Promoting life is being gracious,',
      'Channelling your energies internally is being strong.',
      'Things that mature grow old,',
      'Because they contradict the Dao,',
      'Contradict the Dao, and be brought to an early end.',
    ],
  },

  {
    chapter_number: '56',
    poem: [
      'Those who know talk not,',
      'Those who talk know not.',
      'Blockading its exchanges,',
      'Confining its ideals,',
      'Moderating its ingenuity,',
      'Unraveling its complexity,',
      'Softening its intensity,',
      'Is but merging into its ubiquity,',
      'That is the intricacy of ubiquity.',
      'It cannot be possessed for love,',
      'Cannot be possessed for hate,',
      'Cannot be possessed for profit,',
      'Cannot be possessed for harm,',
      'Cannot be possessed for respect,',
      'Cannot be possessed for despise.',
      'Therefore it is respected by the universe.',
    ],
  },

  {
    chapter_number: '57',
    poem: [
      'Be righteous in governance,',
      'Be unpredictable on the battlefield,',
      'Be unoccupied to master the universe.',
      'How do I know the essence of leadership?',
      'With this:',
      'The world is full of taboo and forbiddance,',
      'And the people is immersed in poverty;',
      'The people is armed with weaponry,',
      'And the nation is clouded with corruption;',
      'The people is preoccupied with professions,',
      'And bizarre obsessions grow out of no where;',
      'Chapters of law and orders are increasingly written,',
      'And thievery is common.',
      'Therefore the master maintains:',
      '“I act not and the people naturally becomes transpired,',
      'I believe in peace and the people naturally becomes righteous,',
      'I am unoccupied and the people naturally becomes prosperous,',
      'I yearn not and the people naturally becomes serene.”',
    ],
  },

  {
    chapter_number: '58',
    poem: [
      'When the governance is idle,',
      'The people is mellow;',
      'When the governance is vigilant,',
      'The people is mischievous.',
      'Adversity! Where fortunes lean,',
      'Fortunes! Where adversity hides.',
      'How can the ultimate be known?',
      'It has no norm!',
      'As righteousness regresses to bewilderments,',
      'Goodwill regresses to bewitchments,',
      'The days become long and hard.',
      'Hence the master is square without being edgy,',
      'Incorrupt without being severe,',
      'Straight without being thoughtless,',
      'Radiant without being glorious.',
    ],
  },

  {
    chapter_number: '59',
    poem: [
      'In governance and management, nothing compares to being conservative.',
      'Only being conservative,',
      'Can withdrawal be advanced.',
      'Advanced withdrawal is putting weight on building Virtue',
      'Put weight on building Virtue,',
      'Then there is nothing insurmountable,',
      'Insurmountable, and limitations are unbeknownst,',
      "When one's limitations are unbeknownst,",
      'One can inspire a nation.',
      'A nation inspired, is a nation that can be viable.',
      'That is being deeply rooted,',
      'In the viability and vision of the Dao.',
    ],
  },

  {
    chapter_number: '60',
    poem: [
      'Governing a nation is like frying small fish.',
      'Approach the world with the Dao,',
      'And evilness will find no spirit.',
      'Not that there are no evil spirits,',
      'But that the spirits will be of no harm;',
      'Not only will the spirits be of no harm,',
      'The master will also be of no harm.',
      'When the master and the subjects bring no harm to each other,',
      'Virtue can hence be returned to another.',
    ],
  },

  {
    chapter_number: '61',
    poem: [
      'Superior nations are positioned downstream.',
      'Where heaven and earth meets,',
      'There the heavenly feminine remains.',
      'Femininity often overcomes masculinity with composure,',
      'Maintaining composure is keeping a low profile.',
      'Therefore when a great nation lurks beneath a small nation,',
      'It can overtake the smaller nation;',
      'When a small nation lurks beneath a great nation,',
      'It can overtake the greater nation.',
      'Therefore stay low in order to conquer,',
      'Or stay low to be able to conquer.',
      'The biggest mistake for a great nation is to be obsessed with domination,',
      'The critical mistake for a small nation is to be obsessed with dominance.',
      'Greatness is achieved only when the desires from both are fulfilled,',
      'Therefore the superior stay low.',
    ],
  },

  {
    chapter_number: '62',
    poem: [
      'The Dao holds the crux to the myriad things,',
      'It is the treasure of goodness,',
      'It is the redeemer of evilness.',
      'Articulate words can influence the economy,',
      'Respectable actions can win the hearts of the people.',
      'How can one be removed from temptation?',
      'Therefore when the leader is chosen,',
      'And the officers are appointed,',
      'Though you may have treasures of honour and chariots of pride to offer,',
      'It compares not to offering a vision in the Dao.',
      'Why is the value of the Dao cherished timelessly?',
      'Without asking and be given,',
      'Having sinned and be forgiven?',
      'Therefore it is cherished by the world.',
    ],
  },

  {
    chapter_number: '63',
    poem: [
      'Act without act,',
      'Work without work,',
      'Taste without taste.',
      'Enlarge the belittled, increase the lessened,',
      'Reward condemnation with Virtue.',
      'Complexity is drawn from simplicity,',
      'Greatness is found in triviality.',
      'Problematic complexities must be resolved in simplicity,',
      'Great accomplishments must be built on trivialities,',
      'Hence the master continues to be unconcerned with great deeds,',
      'Therefore is capable of accomplishing greatness.',
      'Light minded promises draws few believers,',
      'The more simplifications, the more complicated it will become,',
      'Hence the master addresses the complexity.',
      'Therefore may continually avoid complications.',
    ],
  },

  {
    chapter_number: '64',
    poem: [
      'That settled is easily maintained,',
      'That without signs is easily conspired,',
      'That fragile is easily shattered,',
      'That insignificant is easily dispersed.',
      'Act on it before it materializes,',
      'Manage it before it becomes chaotic.',
      'A strapping tree is grown from a tiny sprout;',
      'A sky-scraping tower is built from a modest mound,',
      'A far-reaching journey begins with a small step.',
      'Those who act upon will fail,',
      'Those who hold on will lose.',
      'The master acts not, therefore fails not;',
      'Holds not on, therefore loses not.',
      'Amateurs often fail at the verge of success.',
      'Be focused in the end as in the beginning,',
      'Then there will be no failure.',
      'Hence the master desires not to be desirous,',
      'Treasures not precious possessions.',
      'Learn to be unlearned,',
      'Liberate the people of their past.',
      'Assist the myriad things in returning to their essence,',
      'And not dare act.',
    ],
  },

  {
    chapter_number: '65',
    poem: [
      'The timeless masters of the Dao,',
      'Is not about enlightening the people with it,',
      'But about humbling the people with it.',
      'The people is complicated,',
      'Manage it by managing its intelligence.',
      'Use intelligence to govern a nation, and be the traitor of a nation;',
      'Not use intelligence to govern a nation, and be the blessing of a nation.',
      'Understand these two, and set them as standards.',
      'Being understanding in setting standards,',
      'Is having the intricate Virtue.',
      'The intricate Virtue is profound! Farfetched!',
      'Contra to its objects! And leads towards favourable peacefulness.',
    ],
  },

  {
    chapter_number: '66',
    poem: [
      'Lakes and oceans can be the master of all streams,',
      'Because they are good at staying low,',
      'Therefore they can be master of all streams.',
      'Hence one who desires to be honoured,',
      "Must speak humbly of one's self;",
      "One who desires to lead, must keep one's self behind.",
      'Hence the master is on top yet the people does not feel the weight,',
      'Is in front yet the people is not offended,',
      'Hence the world finds pleasure in pushing the master ahead',
      'Without feeling pushed aside.',
      'It is because the master contests not,',
      'Therefore can be uncontested.',
      'The world says that the Dao is great, but seems useless.',
      'I say that it is great, therefore it seems useless.',
      'If it seemed anything useful,',
      'Time would have diminished its greatness.',
    ],
  },

  {
    chapter_number: '67',
    poem: [
      'I have three precious things, that I hold onto and cherish.',
      'The first is called mercy,',
      'The second is called prudence,',
      'The third is not daring to be on top of the world.',
      'Merciful, therefore can be courageous;',
      'Prudent, therefore can be generous;',
      'Not daring to be on top of the world,',
      'Therefore can become instrumental and respectable.',
      'When without mercy and still courageous,',
      'Without prudence and still generous,',
      'Without reservation and still forging ahead, futility!',
      'With mercy, battles will be won,',
      'Defence will be secure,',
      'The heavens will come to your rescue, and protection in its mercy.',
    ],
  },

  {
    chapter_number: '68',
    poem: [
      'Great gladiators are not violent,',
      'Great warriors are not enraged,',
      'Great champions remain uncontested,',
      'Great leaders act with humility.',
      'That is the Virtue of not contesting,',
      'That is the power of leadership,',
      'That is the ultimate unity with timelessness.',
    ],
  },

  {
    chapter_number: '69',
    poem: [
      'There is a saying in the battlefield,',
      '“Dare not be the host thus be the guest,',
      'Dare not advance an inch thus retreat a foot.”',
      'That is to move without moves,',
      'Be armed without arms,',
      'Cast out without out-casting,',
      'Be forceful without forces.',
      "There is no greater fault than underestimating one's opponent,",
      "To underestimate one's opponent is to lose one's reservation.",
      'Therefore upon the clashing of the forces,',
      'Those who are reserved are victorious!',
    ],
  },

  {
    chapter_number: '70',
    poem: [
      'These words are easy to understand, and easy to follow.',
      'Yet for worldly people, none can understand, none can follow.',
      'Words make legends,',
      'Feats make heroes.',
      'Because in this there is nothing to be known, hence it is unknown.',
      'Those who know are rare, those who abide are respectable,',
      'Hence the master bears humility in apparels and treasuries at heart.',
    ],
  },

  {
    chapter_number: '71',
    poem: [
      'Knowing that you do not know, is superiority;',
      'Not knowing this knowledge, is defectiveness.',
      'Only by defecting defectives,',
      'Can one be void of defectiveness.',
      'The master is void of defectiveness,',
      'Because of the defecting of defectives',
      'Hence is void of defectiveness.',
    ],
  },

  {
    chapter_number: '72',
    poem: [
      'When the people is not threatened by the imposing dignity,',
      "Dignity is imposed! Without intruding the people's dwellings,",
      "Without dejecting the people's creations.",
      'Because of not dejecting,',
      'Hence is not dejected.',
      'Hence the master is introspective, and not professing.',
      'Self-loving, and not self-righteous.',
      'Therefore liberated and resolved.',
    ],
  },

  {
    chapter_number: '73',
    poem: [
      'Courageous in daring and kill,',
      'Courageous in not daring and live.',
      'These two are sometimes favourable, sometimes harmful.',
      'What the heavens detest,',
      'Who knows?',
      'Hence the master addresses the complexity.',
      'The heavenly Dao:',
      'Contest not and master winning,',
      'Speak not and master oration,',
      'Summon not and it comes naturally,',
      'Be honest and master intrigue.',
      'The meshes of the heavenly dragnet is extensive,',
      'It may be sparse, nothing escapes its netting.',
    ],
  },

  {
    chapter_number: '74',
    poem: [
      'When people are not threatened by death,',
      'Why intimidate them with death?',
      'One who causes the people to be constantly threatened by death,',
      'And bewitched with bewilderments, must be seized and executed,',
      'Who dares?',
      'Usually there are executioners who executes,',
      "But those who assume the executioner's job to execute,",
      "Is said to be like assuming the carpenter's job to carve wood.",
      "Those who assume the carpenter's job to carve wood,",
      'Seldom avoid hurting their hands.',
    ],
  },

  {
    chapter_number: '75',
    poem: [
      "People's poverty,",
      'Is caused by parasitic exploitation by superiors,',
      'Hence there is poverty.',
      "People's complicatedness,",
      'Is caused by ambitions of superiors,',
      'Hence there are complications.',
      "People's willingness to sacrifice,",
      'Is because of the weight given to life,',
      'Hence there are sacrifices.',
      'Only those who are not ambitious for achievements in life,',
      'Are truly capable of appreciating life.',
    ],
  },

  {
    chapter_number: '76',
    poem: [
      'People are born gentle and fragile,',
      'They die stiff and tough.',
      'The myriad things, plants and trees, are born tender and crisp,',
      'They die dried and withered.',
      'Therefore those who are stiff and tough are followers of death,',
      'Those who are gentle and fragile are followers of life.',
      'Hence when the armed forces are strong the nation is not successful,',
      'When the resources are strong the arms are naturally forceful.',
      'It is with great strength when one stays low,',
      'It is with gentleness and fragility when one can assume superiority.',
    ],
  },

  {
    chapter_number: '77',
    poem: [
      'The heavenly Dao,',
      'Is like the arching bow!',
      'That on top is repressed,',
      'That below is held high;',
      'The excessive is expended,',
      'The deprived is supplemented.',
      'The way of the Dao is heavenly,',
      'It is to supplement the deprived at the expense of the excessive.',
      'The way of the people is different,',
      'It is to proffer the excessive at the expense of the deprived.',
      'How then can there be any excess to offer to the world?',
      'There is none but the Dao.',
      'Hence the master acts without presumption,',
      'Accomplishes and not dwell,',
      "That is being undesirous in showing-off one's capabilities!",
    ],
  },

  {
    chapter_number: '78',
    poem: [
      'Of all gentleness and submissiveness in the world',
      'Nothing compares to water,',
      'And to tackle stiffness and toughness there is nothing better,',
      'There is no easier substitution.',
      'Be submissive to overcome dominance,',
      'Be gentle to overcome toughness,',
      'There is none in the world who knows not,',
      'There is none who can follow.',
      'Therefore the master says,',
      "“Accepting the nation's shame, is being stately;",
      "Accepting the nation's adversities, is being majestic.”",
      'Righteous words seem contradictory.',
    ],
  },

  {
    chapter_number: '79',
    poem: [
      'When hateful hostility is resolved,',
      'There will be lingering hatred,',
      'How can this be cured?',
      'Hence the master holds onto supporting agreements,',
      'Without holding anyone responsible.',
      'Those with Virtue exert effort on working out agreements,',
      'Those without Virtue exert effort on scrutinizing the disagreements.',
      'The Dao is unbiased,',
      'It will always bring cure to the people.',
    ],
  },

  {
    chapter_number: '80',
    poem: [
      'A small nation has a small population,',
      'Yet even without state of the art instruments to work with,',
      'People would rather sacrifice themselves than to migrate away.',
      'Even though there are vessels and vehicles of travel,',
      'There is none who takes the opportunity;',
      'Even though there are national guards,',
      'They are not lined up for inspection;',
      'People revert to simple means of measure with straps and knots.',
      'Indulge their desires and aspirations,',
      'Adorn their attires and outfits,',
      'Secure their place and quarters,',
      'Console their beliefs and customaries.',
      'Then even if the neighbouring nation is within sight,',
      'And the crowing and barking can be heard,',
      'People retire of old age without longing to give service to the other.',
    ],
  },

  {
    chapter_number: '81',
    poem: [
      'Truthful words are not pleasant,',
      'Pleasant words are not trustworthy;',
      'Those who are good do not dispute,',
      'Those who are disputatious are not good;',
      'Those who know are not learned,',
      'Those who are learned do not know.',
      'The Sage does not store up things,',
      'The more he does for people, the more he has;',
      'The more he gives, the more he gains.',
      'The Way of Heaven,',
      'Is benefitting, not harming.',
      'The Way of the Sage,',
      'Is acting, not contending.',
    ],
  },
];

export const tao_zh: Tao[] = [
  {
    chapter_number: '第一章',
    poem: [
      '道可道，非恆道；',
      '名可名，非恆名。',
      '無名天地之始；',
      '有名萬物之母。',
      '故，',
      '恆無，欲也，以觀其妙；',
      '恆有，欲也，以觀其徼。',
      '此兩者同出而異名，',
      '同謂之玄。',
      '玄之又玄，眾妙之門。',
    ],
  },

  {
    chapter_number: '第二章',
    poem: [
      '天下皆知美之爲美，',
      '斯惡已；',
      '皆知善之爲善，',
      '斯不善已。',
      '故',
      '有無相生，',
      '難易相成，',
      '長短相形，',
      '高下相傾，',
      '音聲相和，',
      '前後相隨。',
      '是以',
      '聖人處無爲之事，',
      '行不言之敎，',
      '萬物作焉而不辭，',
      '生而不有，',
      '爲而不恃，',
      '功成而弗居。',
      '夫唯弗居，是以不去。',
    ],
  },

  {
    chapter_number: '第三章',
    poem: [
      '不尙賢，',
      '使民不爭。',
      '不貴難得之貨，',
      '使民不爲盜。',
      '不見可欲，',
      '使民心不亂。',
      '是以聖人之治，',
      '虛其心，',
      '實其腹，',
      '弱其志，',
      '強其骨。',
      '常使民無知無欲，',
      '使夫智者不敢為也。',
      '為無為，',
      '則無不治。',
    ],
  },

  {
    chapter_number: '第四章',
    poem: [
      '道沖，',
      '而用之或不盈。',
      '淵兮，似萬物之宗。',
      '挫其銳，',
      '解其紛，',
      '和其光，',
      '同其塵。',
      '湛兮，似或存。',
      '吾不知誰之子，',
      '象帝之先。',
    ],
  },

  {
    chapter_number: '第五章',
    poem: [
      '天地不仁，',
      '以萬物為芻狗；',
      '聖人不仁，',
      '以百姓為芻狗。',
      '天地之閒其猶橐籥乎？',
      '虛而不屈，',
      '動而愈出。',
      '多言數窮，',
      '不如守中。',
    ],
  },

  {
    chapter_number: '第六章',
    poem: [
      '谷神不死，是謂玄牝。',
      '玄牝之門，是謂天地根。',
      '綿綿若存，用之不勤。',
    ],
  },

  {
    chapter_number: '第七章',
    poem: [
      '天長地久。',
      '天地所以能長且久者，',
      '以其不自生，',
      '故能長生。',
      '是以聖人後其身',
      '而身先，',
      '外其身',
      '而身存。',
      '非以其無私邪？',
      '故能成其私。',
    ],
  },

  {
    chapter_number: '第八章',
    poem: [
      '上善若水。',
      '水善利萬物而不爭，',
      '處眾人之所惡，',
      '故幾於道。',
      '居善地，',
      '心善淵，',
      '與善仁，',
      '言善信，',
      '正善治，',
      '事善能，',
      '動善時。',
      '夫唯不爭，',
      '故無尤。',
    ],
  },

  {
    chapter_number: '第九章',
    poem: [
      '持而盈之，不如其已。',
      '揣而銳之，不可常保。',
      '金玉滿堂，莫之能守。',
      '富貴而驕，自遺其咎。',
      '功遂身退，天之道。',
    ],
  },

  {
    chapter_number: '第十章',
    poem: [
      '載營魄抱一，',
      '能無離乎？',
      '專氣致柔，',
      '能嬰兒乎？',
      '滌除玄覽，',
      '能無疵乎？',
      '愛民治國，',
      '能無知乎？',
      '天門開闔，',
      '能為雌乎？',
      '明白四達，',
      '能無爲乎？',
      '生之畜之，',
      '生而不有，',
      '為而不恃，',
      '長而不宰，',
      '是謂玄德 。',
    ],
  },

  {
    chapter_number: '第十一章',
    poem: [
      '三十輻共一轂，',
      '當其無，有車之用。',
      '埏埴以為器，',
      '當其無，有器之用。',
      '鑿戶牖以為室，',
      '當其無，有室之用。',
      '故有之以為利，',
      '無之以為用。',
    ],
  },

  {
    chapter_number: '第十二章',
    poem: [
      '五色令人目盲，',
      '五音令人耳聾，',
      '五味令人口爽，',
      '馳騁畋獵令人心發狂，',
      '難得之貨令人行妨。',
      '是以聖人為腹不為目，',
      '故去彼取此。',
    ],
  },

  {
    chapter_number: '第十三章',
    poem: [
      '寵辱若驚，',
      '貴大患若身。',
      '何謂寵辱若驚？',
      '寵為下。',
      '得之若驚，失之若驚，',
      '是謂寵辱若驚。',
      '何謂貴大患若身？',
      '吾所以有大患者，為吾有身；',
      '及吾無身，吾有何患？',
      '故貴以身為天下，',
      '若可寄天下。',
      '愛以身為天下，',
      '若可託天下。',
    ],
  },

  {
    chapter_number: '第十四章',
    poem: [
      '視之不見，名曰夷；',
      '聽之不聞，名曰希；',
      '摶之不得，名曰微。',
      '此三者不可致詰，故混而為一。',
      '其上不皦，其下不昧，',
      '繩繩不可名，復歸於無物，',
      '是謂無狀之狀，無物之象，',
      '是謂惚恍。',
      '迎之不見其首，隨之不見其後。',
      '執今之道以御今之有，能知古始，',
      '是謂道紀。',
    ],
  },

  {
    chapter_number: '第十五章',
    poem: [
      '古之善為道者，微妙',
      '玄達，深不可識。',
      '夫唯不可識，故強為之容。',
      '豫兮，若冬涉川；',
      '猶兮，若畏四鄰；',
      '儼兮，其若客；',
      '渙兮，若冰之將釋；',
      '敦兮，其若樸；',
      '曠兮，其若谷；',
      '渾兮，其若濁。',
      '孰能濁以靜之徐清。',
      '孰能安以動之徐生。',
      '保此道不欲盈。',
      '夫唯不盈，故能蔽而新成。',
    ],
  },

  {
    chapter_number: '第十六章',
    poem: [
      '致虛極；守靜篤。',
      '萬物並作，',
      '吾以觀復。',
      '夫物芸芸，各復歸其根，',
      '歸根曰靜，',
      '是謂復命；',
      '復命曰常，',
      '知常曰明。',
      '不知常妄作，凶。',
      '知常容。',
      '容乃公，',
      '公乃王，',
      '王乃天，',
      '天乃道，',
      '道乃久，',
      '沒身不殆。',
    ],
  },

  {
    chapter_number: '第十七章',
    poem: [
      '太上，下知有之；',
      '其次，親而譽之；',
      '其次畏之；',
      '其次侮之。',
      '信不足焉，有不信焉。',
      '悠兮，其貴言，',
      '功成事遂，',
      '百姓皆謂我自然。',
    ],
  },

  {
    chapter_number: '第十八章',
    poem: [
      '大道廢，有仁義；',
      '智慧出，有大偽；',
      '六親不和有孝慈，',
      '國家昏亂有忠臣。',
    ],
  },

  {
    chapter_number: '第十九章',
    poem: [
      '絕聖棄智，民利百倍；',
      '絕仁棄義，民復孝慈；',
      '絕巧棄利，盜賊無有；',
      '此三者，以為文不足，',
      '故令有所屬：',
      '見素抱樸，',
      '少私寡欲。',
    ],
  },

  {
    chapter_number: '第二十章',
    poem: [
      '絕學無憂。',
      '唯之與阿，相去幾何？',
      '善之與惡，相去何若？',
      '人之所畏，不可不畏？',
      '荒兮其未央哉！',
      '眾人熙熙，',
      '如享太牢，',
      '如登春臺。',
      '我獨泊兮其未兆，',
      '若嬰兒之未孩，',
      '乘乘兮若無所歸。',
      '眾人皆有餘，',
      '而我獨若遺。',
      '我愚人之心也哉！沌沌兮！',
      '俗人昭昭，我獨昏昏；',
      '俗人察察，我獨悶悶。',
      '忽兮其若晦，',
      '寂兮似無所止。',
      '眾人皆有以，我獨頑且鄙。',
      '我獨異於人，',
      '而貴求食於母。',
    ],
  },

  {
    chapter_number: '第二十一章',
    poem: [
      '孔德之容，',
      '唯道是從。',
      '道之為物，',
      '惟恍惟惚。',
      '惚兮恍其中有象；',
      '恍兮惚其中有物。',
      '窈兮冥兮，',
      '其中有精；',
      '其精甚真，其中有信。',
      '自古及今，',
      '其名不去，',
      '以閱眾甫。',
      '吾何以知眾甫之然哉？',
      '以此。',
    ],
  },

  {
    chapter_number: '第二十二章',
    poem: [
      '曲則全，',
      '枉則直，',
      '窪則盈，',
      '弊則新，',
      '少則得，',
      '多則惑，',
      '是以聖人抱一，',
      '為天下式。',
      '不自見故明，',
      '不自伐故彰，',
      '不自是故有功，',
      '不自矜故長。',
      '夫惟不爭，',
      '故天下莫能與之爭。',
      '古之所謂曲則全者，',
      '豈虛言哉！',
      '誠全而歸之。',
    ],
  },

  {
    chapter_number: '第二十三章',
    poem: [
      '希言自然。',
      '故飄風不終朝，',
      '驟雨不終日。',
      '孰為此者？',
      '天地尚不能久，',
      '而況於人乎？',
      '故從事於道者，',
      '道者同於道，',
      '德者同於德，',
      '失者同於失。',
      '同於道者，道亦樂得之；',
      '同於德者，德亦樂得之；',
      '同於失者，失亦樂得之。',
      '信不足焉，',
      '有不信焉。',
    ],
  },

  {
    chapter_number: '第二十四章',
    poem: [
      '跂者不立，',
      '跨者不行，',
      '自見者不明，',
      '自是者不彰。',
      '自伐者無功，',
      '自矜者不長。',
      '其在道也，',
      '曰餘食贅行。',
      '物或惡之，',
      '故有道者不處也。',
    ],
  },

  {
    chapter_number: '第二十五章',
    poem: [
      '有物混成，',
      '先天地生，',
      '寂兮寥兮，',
      '獨立而不改，',
      '周行而不殆，',
      '可以為天下母。',
      '吾不知其名，',
      '字之曰道，',
      '強為之名曰大。',
      '大曰逝，',
      '逝曰遠。',
      '遠曰反。',
      '故道大，',
      '天大，',
      '地大，',
      '王亦大。',
      '域中有四大，',
      '而王處一焉。',
      '人法地，',
      '地法天，',
      '天法道，',
      '道法自然。',
    ],
  },

  {
    chapter_number: '第二十六章',
    poem: [
      '重為輕根，',
      '靜為躁君，',
      '是以君子終日行不離輜重；',
      '雖有榮觀，',
      '燕處超然。',
      '奈何以萬乘之主，',
      '而身輕天下？',
      '輕則失臣，',
      '躁則失君。',
    ],
  },

  {
    chapter_number: '第二十七章',
    poem: [
      '善行，無轍跡；',
      '善言，無瑕謫；',
      '善計，不用籌策；',
      '善閉，無關鍵而不可開；',
      '善結，無繩約而不可解。',
      '是以聖人常善救人，',
      '故無棄人；',
      '善救物，',
      '故無棄物，',
      '是謂襲明。',
      '故善人，不善人之師；',
      '不善人，善人之資。',
      '不貴其師，',
      '不愛其資，',
      '雖智大迷。',
      '是謂要妙。',
    ],
  },

  {
    chapter_number: '第二十八章',
    poem: [
      '知其雄，',
      '守其雌，',
      '為天下谿。',
      '為天下谿，常德不離，',
      '復歸於嬰兒。',
      '知其白，',
      '守其黑，',
      '為天下式。',
      '為天下式，常德不忒，',
      '復歸於無極。',
      '知其榮，',
      '守其辱，',
      '為天下谷。',
      '為天下谷，常德乃足，',
      '復歸於朴。',
      '朴散則為器，',
      '聖人用之則為官長。',
      '故大制不割。',
    ],
  },

  {
    chapter_number: '第二十九章',
    poem: [
      '將欲取天下而為之，',
      '吾見其不得已。',
      '天下神器，',
      '不可為也。',
      '為者敗之，',
      '執者失之。',
      '故物或行或隨，',
      '或呴或吹，',
      '或強或羸，',
      '或載或隳。',
      '是以聖人去甚。',
      '去奢、去泰。',
    ],
  },

  {
    chapter_number: '第三十章',
    poem: [
      '以道佐人主者，',
      '不以兵強天下，',
      '其事好還。',
      '師之所處，荊棘生焉。',
      '大軍之後，必有凶年。',
      '故善者果而已矣，',
      '不敢以取強。',
      '果而勿矜，',
      '果而勿伐，',
      '果而勿驕，',
      '果而不得已，',
      '果而勿強。',
      '物壯則老，',
      '是謂不道，',
      '不道早已。',
    ],
  },

  {
    chapter_number: '第三十一章',
    poem: [
      '夫佳兵者，不祥之器，',
      '物或惡之，',
      '故有道者不處。',
      '是以君子居則貴左，',
      '用兵則貴右。',
      '兵者，不祥之器，',
      '非君子之器。',
      '不得已而用之，',
      '恬淡為上，',
      '勝而不美；',
      '而美之者，是樂殺人也。',
      '夫樂殺人者，',
      '不可得志於天下矣。',
      '故吉事尚左，',
      '凶事尚右。',
      '是以偏將軍處左，',
      '上將軍處右，',
      '以喪禮處之。',
      '殺人之眾，以悲哀蒞之。',
      '戰勝，以喪禮處之。',
    ],
  },

  {
    chapter_number: '第三十二章',
    poem: [
      '道常無名。',
      '朴雖小，',
      '天下不敢臣。',
      '候王若能守，',
      '萬物將自賓。',
      '天地相合，',
      '以降甘露，',
      '人莫之令而自均。',
      '始制有名；',
      '名亦既有，夫亦將知止；',
      '知止所以不殆。',
      '譬道之在天下，',
      '由川谷之於江海。',
    ],
  },

  {
    chapter_number: '第三十三章',
    poem: [
      '知人者智，',
      '自知者明。',
      '勝人者有力，',
      '自勝者強。',
      '知足者富，',
      '強行者有志，',
      '不失其所者久，',
      '死而不亡者壽。',
    ],
  },

  {
    chapter_number: '第三十四章',
    poem: [
      '大道汎兮，',
      '其可左右。',
      '萬物恃之以生而不辭，',
      '功成不名有。',
      '衣被萬物而不為主，',
      '常無欲，',
      '可名於小；',
      '萬物歸焉而不為主，',
      '可名於大。',
      '是以聖人終不為大，',
      '故能成其大。',
    ],
  },

  {
    chapter_number: '第三十五章',
    poem: [
      '執大象，',
      '天下往；',
      '往而不害，',
      '安平泰。',
      '樂與餌，',
      '過客止。',
      '道之出口，',
      '淡乎無味，',
      '視之不可見，',
      '聽之不可聞，',
      '用之不可既。',
    ],
  },

  {
    chapter_number: '第三十六章',
    poem: [
      '將欲歙之，必固張之；',
      '將欲弱之，必固強之；',
      '將欲廢之，必固興之；',
      '將欲奪之，必固與之。',
      '是謂微明，',
      '柔勝剛弱勝強。',
      '魚不可脫於淵，',
      '國之利器不可以示人。',
    ],
  },

  {
    chapter_number: '第三十七章',
    poem: [
      '道常無為而無不為。',
      '侯王若能守，',
      '萬物將自化；',
      '化而欲作，',
      '吾將鎮之以無名之樸；',
      '無名之樸，亦將不欲；',
      '不欲以靜，',
      '天下將自正。',
    ],
  },

  {
    chapter_number: '第三十八章',
    poem: [
      '上德不德，',
      '是以有德；',
      '下德不失德，',
      '是以無德。',
      '上德無為而無以為，',
      '下德為之而有以為。',
      '上仁為之而無以為。',
      '上義為之而有以為。',
      '上禮為之而莫之應，',
      '則攘臂而仍之。',
      '故失道而後德，',
      '失德而後仁，',
      '失仁而後義，',
      '失義而後禮。',
      '夫禮者，',
      '忠信之薄而亂之首也；',
      '前識者，',
      '道之華而愚之始也。',
      '是以大丈夫處其厚，',
      '不處其薄；',
      '居其實，不居其華。',
      '故去彼取此。',
    ],
  },

  {
    chapter_number: '第三十九章',
    poem: [
      '昔之得一者：',
      '天得一以清，',
      '地得一以靈，',
      '神得一以寧，',
      '谷得一以盈，',
      '萬物得一以生，',
      '侯王得一以為天下貞，',
      '其致之一也。',
      '天無以清，將恐裂；',
      '地無以寧，將恐發；',
      '神無以靈，將恐歇；',
      '谷無以盈，將恐竭；',
      '萬物無以生，將恐滅；',
      '侯王無以貞貴高，',
      '將恐蹙。',
      '故貴以賤為本，',
      '高以下為基。',
      '侯王自謂孤、寡不榖。',
      '此其以賤為本也？非乎？',
      '故致數車無車。',
      '不欲琭琭如玉，',
      '落落如石。',
    ],
  },

  {
    chapter_number: '第四十章',
    poem: ['反者道之動，', '弱者道之用。', '天下萬物生於有，', '有生於無。'],
  },

  {
    chapter_number: '第四十一章',
    poem: [
      '上士聞道，勤而行之；',
      '中士聞道，若存若亡；',
      '下士聞道，大笑之，',
      '不笑不足以為道！',
      '故建言有之：',
      '明道若昧，',
      '進道若退，',
      '夷道若類，',
      '上德若谷，',
      '大白若辱，',
      '廣德若不足，',
      '建德若偷，',
      '質直若渝，',
      '大方無隅，',
      '大器晚成，',
      '大音希聲，',
      '大象無形。',
      '夫惟道，善貸且成。',
    ],
  },

  {
    chapter_number: '第四十二章',
    poem: [
      '道生一，',
      '一生二，',
      '二生三，',
      '三生萬物。',
      '萬物負陰而抱陽，',
      '沖氣以為和。',
      '(人之所惡，',
      '孤、寡、不榖，',
      '而王公以為稱。)',
      '故物，或損之而益，',
      '或益之而損。',
      '人之所教，我亦教之：',
      '強梁者不得其死，',
      '吾將以為教父。',
    ],
  },

  {
    chapter_number: '第四十三章',
    poem: [
      '天下之至柔，',
      '馳騁天下之至堅，',
      '無有入於無間，',
      '吾是以知無為之有益。',
      '不言之教，',
      '無為之益，',
      '天下希及之。',
    ],
  },

  {
    chapter_number: '第四十四章',
    poem: [
      '名與身孰親？',
      '身與貨孰多？',
      '得與亡孰病？',
      '是故甚愛必大費，',
      '多藏必厚亡。',
      '知足不辱，',
      '知止不殆，可以長久。',
    ],
  },

  {
    chapter_number: '第四十五章',
    poem: [
      '大成若缺, ',
      '其用不敝；',
      '大盈若沖，',
      '其用不窮。',
      '大直若屈，',
      '大巧若拙，',
      '大辯若訥。',
      '躁勝寒，',
      '靜勝熱，',
      '清靜為天下正。',
    ],
  },

  {
    chapter_number: '第四十六章',
    poem: [
      '天下有道，',
      '卻走以糞；',
      '天下無道，',
      '戎馬生於郊。',
      '罪莫大於可欲，',
      '禍莫大於不知足，',
      '咎莫大於欲得。',
      '故知之足，常足。',
    ],
  },

  {
    chapter_number: '第四十七章',
    poem: [
      '天下有道，',
      '不出戶，',
      '知天下；',
      '不窺牖，',
      '見天道。',
      '其出彌遠，其知彌少。',
      '是以聖人不行而知，',
      '不見而名，',
      '不為而成。',
    ],
  },

  {
    chapter_number: '第四十八章',
    poem: [
      '為學日益，',
      '為道日損；',
      '損之又損，',
      '以至於無為；',
      '無為而無不為矣。',
      '故取天下者，',
      '常以無事；',
      '及其有事，',
      '不足以取天下。',
    ],
  },

  {
    chapter_number: '第四十九章',
    poem: [
      '聖人無常心，',
      '以百姓心為心。',
      '善者吾善之，',
      '不善者吾亦善之。',
      '德善矣，',
      '信者吾信之，',
      '不信者吾亦信之，',
      '德信矣。',
      '聖人在天下惵惵，',
      '為天下渾其心。',
      '百姓皆注其耳目，',
      '聖人皆孩之。',
    ],
  },

  {
    chapter_number: '第五十章',
    poem: [
      '出生入死。',
      '生之徒十有三；',
      '死之徒十有三，',
      '民之生，動之死地，',
      '亦十有三。',
      '夫何故？',
      '以其生生之厚。',
      '蓋聞善攝生者，',
      '陸行不遇兕虎，',
      '入軍不被甲兵；',
      '兕無所投其角，',
      '虎無所措其爪，',
      '兵無所容其刃。',
      '夫何故？',
      '以其無死地。',
    ],
  },

  {
    chapter_number: '第五十一章',
    poem: [
      '道生之，',
      '德畜之，',
      '物形之，',
      '勢成之。',
      '是以萬物',
      '莫不尊道而貴德。',
      '道之尊，',
      '德之貴，',
      '夫莫之命而常自然。',
      '故道生之德畜之，',
      '長之育之，',
      '成之熟之，',
      '養之復之；',
      '生而不有，',
      '為而不恃，',
      '長而不宰，',
      '是謂玄德。',
    ],
  },

  {
    chapter_number: '第五十二章',
    poem: [
      '天下有始以為天下母。',
      '既得其母，',
      '以知其子；',
      '既知其子，',
      '復守其母，',
      '沒身不殆。',
      '塞其兌，',
      '閉其門，',
      '終身不勤。',
      '開其兌，',
      '濟其事，',
      '終身不救。',
      '見小曰明，',
      '守柔曰強。',
      '用其光，',
      '復歸其明，',
      '無遺身殃，',
      '是謂習常。',
    ],
  },

  {
    chapter_number: '第五十三章',
    poem: [
      '使我介然有知，',
      '行於大道，',
      '惟施是畏。',
      '大道甚夷，',
      '而民好徑。',
      '朝甚除田甚蕪，',
      '倉甚虛，',
      '服文綵，',
      '帶利劍，',
      '厭飲食，',
      '財貨有餘，',
      '是謂盜夸。',
      '非道也哉！',
    ],
  },

  {
    chapter_number: '第五十四章',
    poem: [
      '善建者不拔，',
      '善抱者不脫，',
      '子孫祭祀不輟。',
      '修之於身，',
      '其德乃真；',
      '修之於家，',
      '其德乃餘；',
      '修之於鄉，',
      '其德乃長；',
      '修之於國，',
      '其德乃豐；',
      '修之於天下，',
      '其德乃普。',
      '故以身觀身，',
      '以家觀家，',
      '以鄉觀鄉，',
      '以國觀國；',
      '以天下觀天下。',
      '吾何以知天下之然哉？',
      '以此。',
    ],
  },

  {
    chapter_number: '第五十五章',
    poem: [
      '含德之厚，',
      '比於赤子。',
      '毒蟲不螫，',
      '猛獸不據，',
      '攫鷙不博。',
      '骨弱筋柔而握固。',
      '未知牝牡之合而全作，',
      '精之至也；',
      '終日號而嗌不嗄，',
      '和之至也。',
      '知和曰常，',
      '知常曰明，',
      '益生曰祥，',
      '心使氣曰強。',
      '物壯則老，',
      '是謂不道，',
      '不道早已。',
    ],
  },

  {
    chapter_number: '第五十六章',
    poem: [
      '知者不言，',
      '言者不知。',
      '塞其兌，',
      '閉其門，',
      '挫其銳，',
      '解其紛，',
      '和其光，',
      '同其塵，',
      '是謂玄同。',
      '不可得而親，',
      '不可得而疏；',
      '不可得而利，',
      '不可得而害；',
      '不可得而貴，',
      '不可得而賤。',
      '故為天下貴。',
    ],
  },

  {
    chapter_number: '第五十七章',
    poem: [
      '以正治國，',
      '以奇用兵，',
      '無事取天下。',
      '吾何以知其然乎？',
      '以此：',
      '天下多忌諱，',
      '而民彌貧；',
      '民多利器，',
      '國家滋昏；',
      '民多技巧，',
      '奇物滋起；',
      '法令滋彰，',
      '盜賊多有。',
      '故聖人云：',
      '我無為而民自化，',
      '我好靜而民自正，',
      '我無事而民自富，',
      '我無欲而民自朴。',
    ],
  },

  {
    chapter_number: '第五十八章',
    poem: [
      '其政悶悶，',
      '其民醇醇；',
      '其政察察，',
      '其民缺缺。',
      '禍兮福所倚，',
      '福兮禍所伏。',
      '孰知其極？',
      '其無正耶。',
      '正復為奇，',
      '善復為妖民之迷，',
      '其日固久。',
      '是以聖人方而不割，',
      '廉而不劌，',
      '直而不肆，',
      '光而不耀。',
    ],
  },

  {
    chapter_number: '第五十九章',
    poem: [
      '治人事天莫如嗇。',
      '夫惟嗇，',
      '是謂早服。',
      '早服謂之重積德，',
      '重積德則無不克，',
      '無不克則莫知其極，',
      '莫知其極，',
      '可以有國。',
      '有國之母，',
      '可以長久。',
      '是謂深根固蒂，',
      '長生久視之道。',
    ],
  },

  {
    chapter_number: '第六十章',
    poem: [
      '治大國若烹小鮮。',
      '以道莅天下，',
      '其鬼不神。',
      '非其鬼不神，',
      '其神不傷人；',
      '非其神不傷人，',
      '聖人亦不傷人。',
      '夫兩不相傷，',
      '故德交歸焉。',
    ],
  },

  {
    chapter_number: '第六十一章',
    poem: [
      '大國者下流。',
      '天下之交，',
      '天下之牝。',
      '牝常以靜勝牡，',
      '以靜為下。',
      '故大國以下小國，',
      '則取小國；',
      '小國以下大國，',
      '則取大國。',
      '故或下以取，',
      '或下而取。',
      '大國大過欲兼畜人，',
      '小國小過欲入事人，',
      '夫兩者各得其所欲，',
      '故大者宜為下。',
    ],
  },

  {
    chapter_number: '第六十二章',
    poem: [
      '道者萬物之奧，',
      '善人之寶，',
      '不善人之所保。',
      '美言可以巿，',
      '尊行可以加人。',
      '人之不善何棄之有！',
      '故立天子，',
      '置三公，',
      '雖有拱璧以先駟馬，',
      '不如坐進此道。',
      '古之所以貴此道者何也？',
      '不曰求以得，',
      '有罪以免邪？',
      '故為天下貴。',
    ],
  },

  {
    chapter_number: '第六十三章',
    poem: [
      '為無為，',
      '事無事，',
      '味無味。',
      '大小多少，',
      '報怨以德。',
      '圖難于其易，',
      '為大于其細。',
      '天下難事必作于易，',
      '天下大事必作于細，',
      '是以聖人終不為大，',
      '故能成其大。',
      '夫輕諾必寡信，',
      '多易必多難，',
      '是以聖人猶難之。',
      '故終無難。',
    ],
  },

  {
    chapter_number: '第六十四章',
    poem: [
      '其安易持，',
      '其未兆易謀，',
      '其脆易破，',
      '其微易散。',
      '為之于未有，',
      '治之于未亂。',
      '合抱之木，生于毫末；',
      '九層之臺起于累土；',
      '千里之行，始于足下。',
      '為者敗之，',
      '執者失之。',
      '聖人無為，故無敗；',
      '無執，故無失。',
      '民之徒事，常于幾成而敗之。',
      '慎終如始，',
      '則無敗事。',
      '是以聖人欲不欲，',
      '不貴難得之貨。',
      '學不學，',
      '復眾人之所過。',
      '以輔萬物之自然，',
      '而不敢為。',
    ],
  },

  {
    chapter_number: '第六十五章',
    poem: [
      '古之善為道者，',
      '非以明民，',
      '將以愚之。',
      '民之難，',
      '治以其智多。',
      '以智治國，國之賊；',
      '不以智治國，國之福。',
      '知此兩者，亦楷式。',
      '能知楷式，',
      '是謂玄德。',
      '玄德深矣，遠矣，',
      '與物反矣，乃至于大順。',
    ],
  },

  {
    chapter_number: '第六十六章',
    poem: [
      '江海所以能為百谷王者，',
      '以其善下之，',
      '故能為百谷王。',
      '是以聖人欲上人，',
      '必以言下之；欲先人，',
      '必以身後之。',
      '是以聖人處上而人不重，',
      '處前而人不害，',
      '是以天下樂推',
      '而不厭。',
      '以其不爭，',
      '故天下莫能與之爭。',
      '天下皆謂我道大，似不肖。',
      '夫惟大，故似不肖。',
      '若肖，',
      '久矣其細也夫。',
    ],
  },

  {
    chapter_number: '第六十七章',
    poem: [
      '我有三寶，持而寶之。',
      '一曰慈，',
      '二曰儉，',
      '三曰不敢為天下先。',
      '慈，故能勇；',
      '儉，故能廣；',
      '不敢為天下先，',
      '故能成器長。',
      '今捨慈且勇，',
      '捨儉且廣，',
      '捨其後且先，死矣！',
      '夫慈，以戰則勝，',
      '以守則固，',
      '天將救之，以慈衛之。',
    ],
  },

  {
    chapter_number: '第六十八章',
    poem: [
      '善為士者不武，',
      '善戰者不怒，',
      '善勝敵者不爭，',
      '善用人者為之下',
      '是謂不爭之德，',
      '是謂用人之力，',
      '是謂配天古之極。',
    ],
  },

  {
    chapter_number: '第六十九章',
    poem: [
      '用兵有言，',
      '吾不敢為主而為客，',
      '不敢進寸而退尺。',
      '是謂行無行，',
      '攘無臂，',
      '扔無敵，',
      '執無兵。',
      '禍莫大於輕敵，',
      '輕敵幾喪吾寶。',
      '故抗兵相加，',
      '哀者勝矣。',
    ],
  },

  {
    chapter_number: '第七十章',
    poem: [
      '吾言甚易知，甚易行。',
      '天下莫能知，莫能行。',
      '言有宗，',
      '事有君。',
      '夫惟無知，是以不我知。',
      '知我者希，則我者貴，',
      '是以聖人被褐懷玉。',
    ],
  },

  {
    chapter_number: '第七十一章',
    poem: [
      '知不知，上；',
      '不知知，病。',
      '夫惟病病，',
      '是以不病。',
      '聖人不病，',
      '以其病病，',
      '是以不病。',
    ],
  },

  {
    chapter_number: '第七十二章',
    poem: [
      '民不畏威，',
      '威至矣無狎其所居，',
      '無厭其所生。',
      '夫惟不厭，',
      '是以不厭。',
      '是以聖人自知，不自見。',
      '自愛，不自貴。',
      '故去彼取此。',
    ],
  },

  {
    chapter_number: '第七十三章',
    poem: [
      '勇於敢則殺，',
      '勇於不敢則活。',
      '此兩者，或利或害。',
      '天之所惡，',
      '孰知其故？',
      '是以聖人猶難之。',
      '天之道，',
      '不爭而善勝，',
      '不言而善應，',
      '不召而自來，',
      '坦然而善謀。',
      '天綱恢恢，',
      '疏而不漏。',
    ],
  },

  {
    chapter_number: '第七十四章',
    poem: [
      '民不畏死，',
      '奈何以死懼之！',
      '若使民常畏死，',
      '而為奇者吾得執而殺之，',
      '孰敢？',
      '常有司殺者殺，',
      '夫代司殺者殺，',
      '是謂代大匠斲。',
      '夫代大匠斲者，',
      '希有不傷手矣。',
    ],
  },

  {
    chapter_number: '第七十五章',
    poem: [
      '民之饑，',
      '以其上食稅之多，',
      '是以饑。',
      '民之難治，',
      '以其上之有為，',
      '是以難治。',
      '民之輕死，',
      '以其求生之厚，',
      '是以輕死。',
      '夫惟無以生為者，',
      '是賢於貴生。',
    ],
  },

  {
    chapter_number: '第七十六章',
    poem: [
      '人之生也柔弱，',
      '其死也堅強。',
      '萬物草木之生也柔脆，',
      '其死也枯槁。',
      '故堅強者死之徒，',
      '柔弱者生之徒。',
      '是以兵強則不勝，',
      '木強則兵。',
      '強大處下，',
      '柔弱處上。',
    ],
  },

  {
    chapter_number: '第七十七章',
    poem: [
      '天之道，',
      '其猶張弓乎！',
      '高者抑之，',
      '下者舉之；',
      '有餘者損之，',
      '不足者補之。',
      '天之道，',
      '損有餘而補不足。',
      '人之道則不然，',
      '損不足以奉有餘。',
      '孰能有餘以奉天下？',
      '唯有道者。',
      '是以聖人為而不恃，',
      '功成而不處，',
      '其不欲見賢耶。',
    ],
  },

  {
    chapter_number: '第七十八章',
    poem: [
      '天下柔弱',
      '莫過於水，',
      '而攻堅強者莫之能勝，',
      '其無以易之。',
      '弱之勝強，',
      '柔之勝剛，',
      '天下莫不知，',
      '莫能行。',
      '故聖人云，',
      '受國之垢，是謂社稷主；',
      '受國之不祥，是謂天下王。',
      '正言若反。',
    ],
  },

  {
    chapter_number: '第七十九章',
    poem: [
      '和大怨，',
      '必有餘怨，',
      '安可以為善？',
      '是以聖人執左契，',
      '而不責於人。',
      '有德司契，',
      '無德司徹。',
      '天道無親，',
      '常與善人。',
    ],
  },

  {
    chapter_number: '第八十章',
    poem: [
      '小國寡民，',
      '使有什伯人之器而不用，',
      '使民重死而不遠徙。',
      '雖有舟輿，',
      '無所乘之；',
      '雖有甲兵，',
      '無所陳之；',
      '使民復結繩而用之。',
      '甘其食，',
      '美其服，',
      '安其居，',
      '樂其俗。',
      '鄰國相望，',
      '雞犬之聲相聞，',
      '民至老死不相往來。',
    ],
  },

  {
    chapter_number: '第八十一章',
    poem: [
      '信言不美，',
      '美言不信；',
      '善者不辯，',
      '辯者不善；',
      '知者不博，',
      '博者不知。',
      '聖人不積，',
      '既以為人，己愈有；',
      '既以與人，己愈多。',
      '天之道，',
      '利而不害。',
      '聖人之道，',
      '為而不爭。',
    ],
  },
];
